config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: 'groups#index', as: :authenticated_root
  end

  unauthenticated do
    root to: 'home#index', as: :unauthenticated_root
  end

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :groups do
    resources :operations
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, :all
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :operations, dependent: :destroy

  validates :name, :icon, presence: true

  def total_spent
    operations.map(&:amount).sum.round(2)
  end
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :name, presence: true
  validates :amount, presence: true, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :operations
  has_many :groups

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all.where(user: current_user).includes(:operations)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user
    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_instance_variables

  def index
    @operations = @group.operations.order(created_at: :desc)
  end

  def new
    @operation = Operation.new
  end

  def create
    @operation = Operation.new(operation_params)
    @operation.user = current_user
    @group.operations.push(@operation)
    if @operation.save
      redirect_to group_operations_path
    else
      render :new
    end
  end

  def destroy
    @operation.destroy
    redirect_to group_operations_path(@group)
  end

  private

  def set_instance_variables
    @group = Group.find_by(user: current_user, id: params[:group_id])
    @groups = Group.all.where(user: current_user)
    @operation = Operation.find(params[:id]) if params[:id]
  end

  def operation_params
    params.require(:operation).permit(:name, :amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/index.html.erb
<div class="groups">
  <div class="groups-header">
    <h1 class="groups-title"> Categories </h1>
    <%= link_to "SIGN OUT", destroy_user_session_path %>

  </div>
  <div class="group-items">
    <% @groups.each do |group| %>
      <%= link_to group_operations_path(group.id) do %>
        <div class="group-item">
          <img src=<%= group.icon %> alt=<%= group.name %>>
          <h2><%= group.name %></h2>
          <p>Total spent:$<span><%= group.total_spent %></span></p>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="add-group">
    <%= link_to new_group_path do %>
      <button class="group-add-button">ADD NEW CATEGORY</button>
    <% end %>
  </div>
</div>

app/views/groups/new.html.erb
<div class="addgroup">
  <div class="addgroup-header">
    <%= link_to "BACK", groups_path %>
    <h1 class="addgroup-title">Add Category</h1>
    <%= link_to "SIGN OUT", destroy_user_session_path %>
  </div>

  <div class="addgroup-form">
    <%= form_for @group, url: groups_path do |f| %>
      <div class="addgroup-form-inputs">
        <div class="addgroup-form-input">
          <%= f.text_field :name, autofocus: true, placeholder:'Name', autocomplete: "name" %>
        </div>

        <div class="addgroup-form-input">
          <%= f.text_field :icon, placeholder:'Add image address', autocomplete: "icon" %>
        </div>
      </div>
      <div class="addgroup-form-submit">
        <%= f.submit "ADD NEW CATEGORY" %>
      </div>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<div class="home">
  <h1 class="home-title">My Budget</h1>
  <div class="home-links">
    <%= link_to "LOG IN", new_user_session_path, class: "home-login"%>
    <%= link_to "SIGN UP", new_user_registration_path, class: "home-signup" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetAppRor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/operations/index.html.erb
<div class="operations">
  <div class="operations-header">
    <%= link_to "BACK", groups_path %>
    <h1 class="operations-title">Operations</h1>
    <%= link_to "SIGN OUT", destroy_user_session_path %>
  </div>

  <div class="operations-body">

    <div class="operations-info">
      <img src=<%= @group.icon %>>
      <span><%= @group.name %></span>
    </div>

    <div class="operations-total">
      <p>Total Amount: <span><strong style="font-weight: 700;">$<%= @group.total_spent %></strong></span></p>
      <%= button_to "Delete Category", @group, method: :delete, class: "delete-button" %>
    </div>
    <table>
      <thead>
        <tr>
          <td>Date</td>
          <td>Name</td>
          <td>Cost</td>
          <td>Actions</td>
        </tr>
      </thead>

      <tbody>
        <% @operations.each do |operation| %>
          <tr>
            <td><%= operation.created_at.strftime("%m-%d-%Y") %></td>
            <td><%= operation.name %></td>
            <td>$<%= operation.amount %></td>
            <td>
              <%= button_to "Delete", group_operation_path(@group, operation), method: :delete, class: "delete-button" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="operation-add">
    <%= link_to new_group_operation_path do %>
      <button class="operation-add-button">ADD NEW OPERATION</button>
    <% end %>
  </div> 
</div>

app/views/operations/new.html.erb
<div class="addoperation-header">
  <%= link_to "BACK", group_operations_path %>
  <h1 class="addoperation-title">Add Operation</h1>
  <%= link_to "SIGN OUT", destroy_user_session_path %>
</div>

<div class="addoperation-form">
  <%= form_for @operation, url: group_operations_path do |f| %>

    <div>
      <div class="addoperation-form-field">
        <%= f.text_field :name, autofocus: true, placeholder:'Name', autocomplete: "name" %>
      </div>

      <div class="addoperation-form-field">
        <%= f.text_field :amount, placeholder:'Amount',autocomplete: "amount" %>
      </div>
  
      <div class="addoperation-form-field">
        <%= f.label :category %><br/>
        <% selected_group = @groups.detect {|g| g.id == params[:group_id].to_i} %>
       <% if selected_group %>
         <%= f.text_field :category, value: selected_group.name, readonly: true %>
       <% else %>
         <%= f.text_field :category %>
       <% end %>
     </div>
    </div>

    <div class="addoperation-form-submit">
      <%= f.submit "ADD NEW OPERATION" %>
    </div>
  <% end %>
</div>